name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.2
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{steps.publish.outputs.script-file}}
    steps:

      - name: Get code
        id: checkingOut-code
        uses: actions/checkout@v3.5.2

      - name: Install dependencies
        id: Installing-Dependencies
        run: npm ci
      
      - name: Build website
        id: Making-a-build
        run: npm run build

      - name: Publishing Outputs
        id: publish
        run: find dist/assets/*.js -type f -execdir echo "::set-output name=script-file::{}" ";"

        #Uploading Artifacts 
      - name: Uploading Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."

      - name: Getting The Output from the Previous Job
        run: echo ${{needs.build.outputs.script-file}}

      # - name: Making a folder for downloading Artifacts
      #   run: mkdir artifacts_downloaded
      - name: Downloading Artifacts
        uses: actions/download-artifact@v2.1.1
        with:
          name: dist-files
          #path: artifacts_downloaded
      - name: Printing the downloaded Artifacts
        run: ls
